replicaCount: 1

bdhost: mysql
dbname: student
dbpassword: root
dbusername: root

requests:
  cpu: "100m"
  memory: "100Mi"

limits:
  cpu: "200m"
  memory: "200Mi"

  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3


