apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: studentapi
  name: studentapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapi
  template:
    metadata:
      labels:
        app: studentapi
    spec:
      containers:
      - image: sebaspp/studentapi:2.1.19
        name: studentapi
        ports:
        - containerPort: 8080
        env: 
        - name: DB_HOST
          value: {{.Values.env.DB_HOST }}
        - name: DB_NAME
          value: {{.Values.env.DB_NAME }}
        - name: DB_PASSWORD
          value: {{.Values.env.DB_PASSWORD }}
        - name: DB_USERNAME
          value: {{.Values.env.DB_USERNAME }}
        startupProbe:
          httpGet:
            path: {{.Values.httpGet.path }}
            port: 8080
          failureThreshold: 30
          periodSeconds: 50
        livenessProbe:
          httpGet:
            path: {{.Values.httpGet.path }}
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 50
          successThreshold: 1
          failureThreshold: 5
        resources: 
          requests:
            cpu: {{.Values.resources.request.cpu}}
            memory: {{.Values.resources.request.memory}}
          limits:
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}